notifications:
  email: false
language: go
go:
- 1.12.x
sudo: false
env:
  - GO111MODULE=on
jobs:
  include:
  - stage: Unit tests
    script:
      - go test ./whisperv6/...
      - go test ./shhclient/...
